// To update list use the htmlCompaniesParser.js from this directory
// Copy/paste on console on the newest newsletter and add the json to this list.

export const states = ['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Federated States of Micronesia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', 'Palau', 'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virgin Island', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'];

export const companies = [
    {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/94d01e69-a6e2-4c17-8681-eefecca01d11.png",
        "name": "Bethnal Green Ventures: The Tech for Good SEIS and EIS Fund 2",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: SEIS and EIS Fund; Equity; Minimum Investment £20,000",
        "taxRelief": "Tax Relief: SEIS and EIS eligible",
        "endDate": "Campaign end-date: 30th September 2019",
        "impactType": "Impact Type: Social and environmental. Current portfolio of 55 active companies cover 13 of the 17 UN SDGs",
        "impactTypeLink": "",
        "desc": "Description: \"Bethnal Green Ventures (BGV) is Europe’s leading early-stage tech for good VC. They back ambitious founders using technology to tackle big social and environmental problems that aim to radically improve millions of lives. Their Tech for Good SEIS and EIS Fund 2 provides investors exposure to high-potential tech for good companies in a diversified portfolio, while benefiting from the advantages of SEIS and EIS tax relief. (For professional and sophisticated investors only.)\"\n\nFund Site & Information Memorandum // BGV Website // BGV Impact Report",
        "links": [{"BGV Website": "https://t.sidekickopen05.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4Y9g1C8qCk-FW56dWm66CTPDl102?t=https%3A%2F%2Fbethnalgreenventures.com%2F&si=7000000001732761&pi=ea978196-1d54-4397-a4e7-beb0be477c6d"}, {"BGV Impact Report": "https://t.sidekickopen05.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4Y9g1C8qCk-FW56dWm66CTPDl102?t=https%3A%2F%2Fs3-eu-west-2.amazonaws.com%2Fwpmedia.outlandish.com%2Fbgv%2Fapp%2Fuploads%2F2019%2F06%2F23183359%2FFINAL_BGV-Learning-and-Impact-Report-2018_24pp.pdf%3Futm_source%3DBGV%26utm_campaign%3Dimpact_report&si=7000000001732761&pi=ea978196-1d54-4397-a4e7-beb0be477c6d"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/dd9c60da-55f5-42e4-a19c-0924d9392aee.png",
        "name": "Climate Edge: Connecting the Emerging Agriculture Market through Data-led technology",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising: £500,000, Pre-money valuation: £2.5 - £3.5m",
        "taxRelief": "Tax Relief: EIS eligible (SEIS allowance already distributed in previous round)",
        "endDate": "Campaign end-date: November 2019",
        "impactType": "Impact Type: Decent Work and Economic Growth (UN Goal #8)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg8",
        "desc": "Description: \"Climate Edge is building a scalable, accessible and standardised database of farmers in the Emerging Agriculture Markets (e.g. Kenya, Colombia, India) to allow agricultural value added service (agri-vas)  providers, such as insurers and financers, to deliver well performing products. We build this database by providing aggregated farming organizations (AFOs) in these countries  with products they want to use, to incentivize them to input high quality farmer data at scale.\" As a social enterprise they reinvest over 50% of profits into achieving their social mission (with climate smart agriculture, data analytics, and climate monitoring & evaluation).",
        "links": [{"Campaign Link": "https://www.climate-kic.org/marketplace/startup/climate-edge/?trl=1-9&pdr=6-10&capital=0-6500000&country=uk--&marketsector&round=seed--series-a--&from&sort=a-z"}, {"Website Link": "https://www.climate-edge.com/"}, {"James@climate-edge.co.uk": "mailto: James@climate-edge.co.uk"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/e9a1c14c-bf00-4206-8611-973dcbf9bfef.jpg",
        "name": "Lean Lunch: Support a sustainable online food delivery service",
        "location": "Leeds",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising: £120,000, Pre-money valuation: £940,000",
        "taxRelief": "Tax Relief: EIS and SEIS eligible",
        "endDate": "Campaign end-date: 18th of August, 2019",
        "impactType": "Impact Type: Responsible Consumption and Production (UN Goal #12)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg12",
        "desc": "Description: \"Lean Lunch is an online food delivery business that aims to improve wellbeing for people and the planet. It delivers delicious, nutritious, chef-prepared, sustainably-packaged food to city centre offices by cargo bike. The company reduces food waste to the minimum through an online pre-ordering system and use only compostable or 100% recyclable pakcaging. Every meal is of high quality and prepared by experienced chefs in cooperation with trained nutritionists. Currently operating in Leeds, they are planning to expand to more cities in the future.\"",
        "links": [{"Campaign Link (CrowdCube)": "https://www.crowdcube.com/companies/lean-lunch/pitches/boLodq"}, {"Website Link": "https://www.leanlunch.co.uk/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/9c936296-a9e0-4b76-b2f8-9e0b607e7948.png",
        "name": "StorEN: Fund a new and more sustainable battery storage system",
        "location": "Stony Brook",
        "region": "New York",
        "investType": "Investment Type: Equity; Pre-money valuation: $28.1m, $252 minimum investment",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 4th of October, 2019",
        "impactType": "Impact Type: Affordable and Clean Energy (UN Goal #7)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"StorEN answers the call for long-lasting, and affordable energy storage by developing evolutionary vanadium flow batteries. Their technology provides the lowest cost-per-cycle on the market. Apart from being a cost-efficient solution the batteries are also efficient, powerful, durable and long-lasting, making them more sustainable than other battery solutions currently available on the market. The battery can be used to store solar energy as well as power from the grid at night, in places with dual rates, when electricity prices are low.\"",
        "links": [{"Campaign Link": "https://www.startengine.com/storen-technologies"}, {"Website Link": "https://www.storen.tech/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/24afdd42-54c0-4c73-b0f1-49138c8b141b.png",
        "name": "Win-Win: Fund a tech company working to gamify giving",
        "location": "Oakland",
        "region": "California",
        "investType": "Investment Type: Convertible equity; Raising up to $1,070,000, $250 minimum investment, 20% discount",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 18 September, 2019",
        "impactType": "Impact Type: Industry, Innovation and Infrastructure (UN Goal #9)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg9",
        "desc": "Description: \"Win-Win is an online platform connecting pro athletes, charities, fans, and brands through integrated gaming mechanics. The concept is to offer a true win-win scenario where athletes host tournaments, users join the tournament by submitting their entries (picks, predictions, etc), they earn points and compete for epic experiences and amazing apparel, and can also voluntarily support a charity chosen by the athlete by making a donation.\"",
        "links": [{"Campaign Link (via Republic)": "https://republic.co/win-win"}, {"Website Link": "http://www.trywinwin.com"}]
    },
    {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/10617a0e-46d2-4f50-b2c7-f091e9d94a31.jpg",
        "name": "Deciwatt: Instant and accessible renewable energy products",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising: £400,000, Pre-money valuation: £2,300,000",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: Unknown (into over-investing - could close soon)",
        "impactType": "Impact Type: Affordable and Clean Energy (UN Goal #7)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"Deciwatt develop renewable energy solutions and the newest product, NowLight creates instant light and power from the pull of a cord. Just one minute of pulling on NowLight’s cord will generate up to two hours of light and when fully charged NowLight will provide up to 50 hours of light, as well as charge mobile devices. It can be used recreationally and has particularly interesting potential in humanitarian aid contexts or for the billions of people worldwide who lack reliable sources of energy or light.\"",
        "links": [{"Website Link": "http://deciwatt.global"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/d2d861e5-4fed-4d29-952e-377fccc5f3b7.png",
        "name": "Doreset Community Energy: ",
        "location": "Dorset",
        "region": "UK",
        "investType": "Investment Type: Bond-style withdrawable equity. Target interest rate 5.5%",
        "taxRelief": "Tax Relief: not EIS eligible",
        "endDate": "Campaign end-date: End of July!",
        "impactType": "Impact Type: Affordable and Clean Energy (UN Goal #7)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"Ethical, local investment, that helps fight climate change, and benefits the community. Install 700kWp of rooftop solar panels, generating reduced-price electricity for schools and hospitals in Dorset. A successful Low Carbon Dorset grant covers 40% of the costs. As part of this grant application, a rigorous procurement exercise was carried out on all elements of the work.\"",
        "links": [{"Website Link": "https://www.dorsetcommunityenergy.org.uk/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/f2c1be5f-30b2-4fa4-917d-c9e1d957a340.png",
        "name": "Black Bee Honey: Supporting British bees and their keepers",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising: £100,000, Pre-money valuation: £786,000",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 13 July, 2019",
        "impactType": "Impact Type: Life on Land (UN Goal #15)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg15",
        "desc": "Description: \"Black Bee Honey, offer a range of award winning, single-origin, raw British Honeys. The company celebrates British honey and British bees, which after nearly dying out, are slowly making a comeback and since launch has seen a healthy increase in honey sold and can be found in over 150 stockists including Ocado, Wholefoods Market, Planet Organic and Sourced Market.\"",
        "links": [{"Campaign Link (CrowdCube)": "https://www.crowdcube.com/companies/black-bee-honey/pitches/bLrmdl"}, {"Website Link": "https://www.blackbeehoney.co"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/bb5a7aad-08d0-4534-9152-3c9032e8c908.png",
        "name": "Jumpstart: Revolutionary solution democratising disaster insurance",
        "location": "Oakland",
        "region": "California",
        "investType": "Investment Type: Convertible equity; Raising up to $1,070,000, $100 minimum investment, 10% discount",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 1 October, 2019",
        "impactType": "Impact Type: Sustainable Cities and Communities (UN Goal #11)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg11",
        "desc": "Description: \"Jumpstart makes disaster insurance fast, simple and affordable by introducing a new product category called parametric insurance. This means, that after the occurrence of a pre-defined event (e.g. earthquake) - the parameter - a lump-sum is paid out right away to all people affected. There are no delays, no paperwork and no visits needed. The insurance is handled by Lloyd’s of London and customers pay a monthly fee to Jumpstart.\"",
        "links": [{"Campaign Link (Republic)": "https://republic.co/jumpstart"}, {"Website Link": "https://www.jumpstartrecovery.com"}]
    },
    {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/c765c23e-7b33-4d5a-aca3-51a7b8724277.jpg",
        "name": "Stablepharma: An invention to stabilise vaccines",
        "location": "Bath",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising £750,000, Pre-money valuation: £20m",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 19 June, 2019",
        "impactType": "Impact Type: Good Health and Well-being (UN Goal # 3)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg3",
        "desc": "Description: \"50% of vaccines are wasted, mainly due to poor refrigeration. Stablepharma's invention is designed to deliver a disruptive solution that can eliminate waste & supply life-saving vaccines to all without refrigeration. Proof of Concept has been achieved & investment is now sought for commercialisation.\"",
        "links": [{"Campaign Link (CrowdCube)": "https://www.crowdcube.com/companies/stablepharma/pitches/qaRjBl"}, {"Website Link": "https://stablepharma.com/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/a8b0068a-c8a4-407e-a635-401262478264.jpg",
        "name": "Rubies in the Rubble: Fund an award winning food waste solution",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising £300,000, Pre-money valuation: £4.8m",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 5 July, 2019",
        "impactType": "Impact Type: Responsible Consumption and Production (UN Goal #12)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg12",
        "desc": "Description: \"Did you know that 1/3 of food produced never reaches our plates? Rubies in the Rubble is on a mission to change this by making award winning condiments from surplus ingredients, that would otherwise have gone to waste.\"",
        "links": [{"Campaign Link (Seedrs)": "https://www.seedrs.com/rubiesintherubble"}, {"Website Link": "http://rubiesintherubble.com"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/b94b45f5-df4d-48a8-93f0-c08b30760d92.jpg",
        "name": "BuyMeOnce: Fund the online shop for long-lasting products",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity; Raising £300,000; Pre-money valuation £2.4m",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 12 June, 2019",
        "impactType": "Impact Type: Responsible Consumption and Production (UN Goal # 12)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg12",
        "desc": "Description: \"BuyMeOnce is sick of badly made products and modern-day throwaway culture. The company offers an industry-leading online marketplace for long-lasting and sustainable products.  Conscious consumerism is about to go mainstream and as a one-stop-shop for eco products, they have a huge opportunity to meet this need.\"",
        "links": [{"Campaign Link (CrowdCube)": "https://www.crowdcube.com/companies/buymeonce/pitches/qDBxEZ"}, {"Website Link": "https://uk.buymeonce.com/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/a3100df3-1ea0-4758-9af5-c8ff1707e6bf.jpg",
        "name": "Electric Blue: Fund electric vehicle charging solution",
        "location": "Cambridge",
        "region": "UK",
        "investType": "Investment Type: 5 year bonds, paying 5% p.a. (min £500, or £1000 for ISA)",
        "taxRelief": "Tax Relief: ISA",
        "endDate": "Campaign end-date: 30 June, 2019",
        "impactType": "Impact Type: Affordable and Clean Energy (UN Goal # 7)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"Electric Blue provides electric vehicle chargers and electric vehicle services into the UK taxi market, for both public and private use. All of their electric vehicle chargers are powered by suppliers providing 100% renewable energy.\"\nNote: This bond supports an innovative new electric vehicle scheme - and is higher risk than other bonds with comparable returns.",
        "links": [{"Campaign Link (Ethex)": "https://www.ethex.org.uk/ElectricBlue"}, {"Website Link": "https://www.electricblueuk.com"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/4a43f121-9dbd-443c-9f70-42a5279a3449.png",
        "name": "InnaMed: Fund new technology to enable personalized at-home medicine",
        "location": "Philadelphia",
        "region": "Pennsylvania",
        "investType": "Investment Type: Convertible equity (an agreement for future equity in the startup). $60 minimum investment, 0% discount. ",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 1 August, 2019",
        "impactType": "Impact Type: Good Health and Wellbeing (UN Goal #3)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg3",
        "desc": "Description: \"InnaMed is developing an at-home blood testing device and remote monitoring software that enable patients to easily communicate quantitative and qualitative health assessments from home. The collected data feeds into algorithms that detect deterioration early and guide treatment decisions, improving outcomes and reducing costs.\"",
        "links": [{"Campaign Link (Republic)": "https://republic.co/innamed"}, {"Website Link": "https://www.innamed.com"}]
    },
    {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/3e3e6bf8-98f8-4c7a-bb50-70c44f83386e.png",
        "name": "RIPPLE: Fund a clean energy ownership platform",
        "location": "London",
        "region": "UK",
        "investType": "Investment Type: Equity (23.21%) for £750,000 / £2.5m valuation",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 14 June, 2019",
        "impactType": "Impact Type: Affordable and Clean Energy (UN Goal 7)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"Ripple is a clean energy ownership platform with an aim to enable people to own new, large scale wind farms and have the clean, low cost, stable priced power they produce supplied to their homes.\"",
        "links": [{"Campaign Link": "https://www.seedrs.com/ripple/sections/idea"}, {"Website Link": "http://www.rippleenergy.com/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/dec2c168-d383-40f9-96c3-28c38b78686e.png",
        "name": "SOLAR FOR SCHOOLS: Fund clean energy ownership",
        "location": "England and Wales",
        "investType": "Investment Type: Bond offer with a return of 5% paid annually",
        "taxRelief": "Tax Relief: ISA",
        "endDate": "Campaign end-date: 30 June, 2019",
        "impactType": "Impact Type: Affordable and Clean Energy & Sustainable Cities and Communities (UN Goals 7 & 11)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg7",
        "desc": "Description: \"Solar for Schools' long-term goal is to see every school in the UK with solar panels, contributing to a more sustainable future. For every £1,000 of bonds you purchase, you will help schools save and earn between one and three times that amount over the lifetime of the solar panels that will be installed on site.\"",
        "links": [{"11": "https://sustainabledevelopment.un.org/sdg11"}, {"Campaign Link": "https://www.ethex.org.uk/solar-for-schools-_2252.html"}, {"Website Link": "https://www.solarforschools.co.uk/funding/cbs"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/f88f3e1d-8a95-4e0c-9683-7723271323b6.jpeg",
        "name": "RIVERSIMPLE: Fund the 'future of mobility' with new electric vehicles",
        "location": "Llandrindod Wells",
        "region": "UK",
        "investType": "Investment Type: Equity (1.26%) for £750,000 / £59m valuation",
        "taxRelief": "Tax Relief: EIS eligible",
        "endDate": "Campaign end-date: 16 June, 2019",
        "impactType": "Impact Type: Industry, Innovation and Infrastructure (UN Goal 9)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg9",
        "desc": "Description: \"Introducing a zero emission electric car powered by hydrogen, offered for a monthly subscription fee that covers insurance, maintenance, recovery, tax and fuel. People use car for 1-3 years and can then renew it or return that car, which will be supplied to a 2nd, 3rd, 4th,... customer.\"",
        "links": [{"Campaign Link": "https://www.seedrs.com/riversimple1/sections/idea"}, {"Website Link": "http://riversimple.com/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/e2127e2f-e896-41e9-8b3c-929deab7503d.png",
        "name": "PENPAL SCHOOLS: Fund cross-cultural project-based learning in schools around the world",
        "location": "Austin",
        "region": "Texas",
        "investType": "Investment Type: Republic’s Crowd SAFE system (an agreement for future equity in the startup, meaning that it can convert to equity in the future). 20% discount on whatever is agreed with VCs.",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 1 May, 2019 (very soon!)",
        "impactType": "Impact Type: Quality Education (UN Goal 4)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg4",
        "desc": "Description: \"With over 320,000 participating students in more than 150 countries, PenPal Schools is leading the project-based learning revolution. Students on PenPal Schools don’t just write to each other - they collaborate globally to design robots, create films, explore careers, and find local solutions to global problems.\"",
        "links": [{"Campaign Link": "https://republic.co/penpal-schools"}, {"Website Link": "https://www.penpalschools.com/"}]
    }, {
        "logo": "https://gallery.mailchimp.com/08707f64623756d8a0ef4c72d/images/5c8e80a9-c4ed-43bf-9174-2d8c0c31a428.jpeg",
        "name": "SMART YEILDS: Fund a data-driven farming solution",
        "location": "Honolulu",
        "region": "Hawaii",
        "investType": "Investment Type: Republic’s Crowd SAFE system (an agreement for future equity in the startup, meaning that it can convert to equity in the future). 20% discount on whatever is agreed with VCs.",
        "taxRelief": "Tax Relief: N/A",
        "endDate": "Campaign end-date: 30 April, 2019 (very soon!)",
        "impactType": "Impact Type: Responsible Production and Consumption (UN Goal 12)",
        "impactTypeLink": "https://sustainabledevelopment.un.org/sdg12",
        "desc": "Description: \"Smart Yields uses big data insights for small farmers in a subscription model to get farmers online quickly, simply and cost effectively. It uses low-cost state of the art technology to provide actionable insights for farms, researchers and their communities in an integrated farm-to-screen solution.”",
        "links": [{"Campaign Link": "https://republic.co/smartyields"}, {"Website Link": "https://smartyields.com/"}]
    }
];
